apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-hqkh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-rhtap-three-component-scenarios-hqkh
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-go-rhtap-three-comayx
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-go-rhtap-three-component-scenarios-hqkh
    weight: null
status: {}
